from yl10klass import Inimene

inimene1 = Inimene("Timmu", "Õunapuu", 5)
inimene2 = Inimene("Joonatan", "Rõngas", 3)
inimene3 = Inimene("Jaanus", "Toots", 1)
inimene1.tutvustus()
inimene2.tutvustus()
inimene3.tutvustus()
inimene1.getmin()
inimene2.getmin()
inimene3.getmin()
inimene1.suurenda_sisselogimiskatsed()
inimene1.suurenda_sisselogimiskatsed()
inimene1.suurenda_sisselogimiskatsed()
inimene2.suurenda_sisselogimiskatsed()
inimene2.suurenda_sisselogimiskatsed()
inimene3.suurenda_sisselogimiskatsed()
inimene1.reset_sisselogimiskatsed()
inimene2.reset_sisselogimiskatsed()
inimene3.reset_sisselogimiskatsed()
input()
